name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: hiroki-it
          template: classic
          base: ""
          config_display: large
          config_timezone: Asia/Tokyo
          plugin_languages: yes
          plugin_languages_analysis_timeout: 60
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_details: lines
          plugin_languages_indepth: yes
          # HTML、CSS、Dockerfile、は対象外とする
          plugin_languages_ignored: html, css, dockerfile, blade, makefile
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
